/* eslint-disable */
// This file is generated by scripts/import_artist_packs.py
// Do not edit by hand; edit JSON in artist-packs/ instead.

import type { ArtistPack } from "@/content/types";

export const generatedAtIso = "2026-02-18T17:53:48.217256+00:00";

export const artistPacks: ArtistPack[] = [
  {
    "artist": {
      "id": "felix",
      "slug": "felix-ipfling",
      "name": "Felix Ipfling",
      "bioPdf": "/artist/felix-ipfling-kurzportrait-2024-09.pdf",
      "bioMarkdown": "Leinwandarbeiten aus dem Felix-Portfolio.",
      "contact": {
        "phone": "0176 21196733",
        "email": "felix@ipfling.de",
        "website": "https://felix-ipfling.de",
        "instagram": "https://instagram.com/felix.ipfling"
      },
      "links": [
        {
          "label": "Website",
          "href": "https://felix-ipfling.de"
        },
        {
          "label": "Instagram",
          "href": "https://instagram.com/felix.ipfling"
        }
      ],
      "exhibitions": []
    },
    "rooms": [
      {
        "id": "room-01",
        "title": "Felix Room 1",
        "theme": "loft",
        "length": 24,
        "width": 24,
        "height": 7.4,
        "accentColor": "#caa563",
        "categoryFilter": [
          "canvas_large",
          "canvas_small",
          "paper",
          "other"
        ],
        "maxArtworks": 10,
        "wallTexture": "/backgrounds/room1-a.jpg",
        "wallTextureAlt": "/backgrounds/room1-b.jpg",
        "floorTexture": "/backgrounds/room1-floor.jpg",
        "ceilingTexture": "/backgrounds/nacht-decke.png"
      },
      {
        "id": "room-02",
        "title": "Felix Room 2",
        "theme": "modern",
        "length": 24,
        "width": 24,
        "height": 7.4,
        "accentColor": "#8fd3ff",
        "categoryFilter": [
          "canvas_large",
          "canvas_small",
          "paper",
          "other"
        ],
        "maxArtworks": 10,
        "wallTexture": "/backgrounds/room3-a.jpg",
        "wallTextureAlt": "/backgrounds/room3-b.jpg",
        "floorTexture": "/backgrounds/room3-floor.jpg",
        "ceilingTexture": "/backgrounds/nacht-decke.png"
      },
      {
        "id": "room-03",
        "title": "Felix Room 3",
        "theme": "castle",
        "length": 24,
        "width": 24,
        "height": 7.4,
        "accentColor": "#d6b45c",
        "categoryFilter": [
          "canvas_large",
          "canvas_small",
          "paper",
          "other"
        ],
        "maxArtworks": 10,
        "wallTexture": "/backgrounds/room2-a.jpg",
        "wallTextureAlt": "/backgrounds/room2-b.jpg",
        "floorTexture": "/backgrounds/room2-floor.jpg",
        "ceilingTexture": "/backgrounds/nacht-decke.png"
      },
      {
        "id": "room-04",
        "title": "Felix Room 4",
        "theme": "loft",
        "length": 24,
        "width": 24,
        "height": 7.4,
        "accentColor": "#caa563",
        "categoryFilter": [
          "canvas_large",
          "canvas_small",
          "paper",
          "other"
        ],
        "maxArtworks": 10,
        "wallTexture": "/backgrounds/room1-a.jpg",
        "wallTextureAlt": "/backgrounds/room1-b.jpg",
        "floorTexture": "/backgrounds/room1-floor.jpg",
        "ceilingTexture": "/backgrounds/nacht-decke.png"
      },
      {
        "id": "room-05",
        "title": "Felix Room 5",
        "theme": "modern",
        "length": 24,
        "width": 24,
        "height": 7.4,
        "accentColor": "#8fd3ff",
        "categoryFilter": [
          "canvas_large",
          "canvas_small",
          "paper",
          "other"
        ],
        "maxArtworks": 10,
        "wallTexture": "/backgrounds/room3-a.jpg",
        "wallTextureAlt": "/backgrounds/room3-b.jpg",
        "floorTexture": "/backgrounds/room3-floor.jpg",
        "ceilingTexture": "/backgrounds/nacht-decke.png"
      }
    ],
    "artworks": []
  },
  {
    "artist": {
      "id": "luca",
      "slug": "luca-schweiger",
      "name": "Luca Schweiger",
      "bioPdf": "",
      "bioMarkdown": "Arbeiten von Luca Schweiger.",
      "contact": {
        "email": "lschweiger03@gmail.com"
      },
      "links": [],
      "exhibitions": []
    },
    "rooms": [
      {
        "id": "room-01",
        "title": "Luca Room 1",
        "theme": "modern",
        "length": 24,
        "width": 24,
        "height": 7.4,
        "accentColor": "#b7b0a6",
        "categoryFilter": [
          "paper",
          "other"
        ],
        "maxArtworks": 8,
        "wallTexture": "/backgrounds/room1-a.jpg",
        "wallTextureAlt": "/backgrounds/room1-b.jpg",
        "floorTexture": "/backgrounds/room1-floor.jpg",
        "ceilingTexture": "/backgrounds/nacht-decke.png"
      }
    ],
    "artworks": [
      {
        "id": "luca-gelbes-cover",
        "artistId": "luca",
        "title": "Gelbes Cover",
        "year": 2025,
        "medium": "mixed media auf Papier",
        "widthCm": 41,
        "heightCm": 59,
        "priceEur": 600,
        "category": "paper",
        "status": "available",
        "zoneId": 0,
        "images": {
          "texture": "/artist/luca/images/01_Gelbes_Cover.jpg.jpg",
          "full": "/artist/luca/images/01_Gelbes_Cover.jpg.jpg",
          "thumb": "/artist/luca/images/01_Gelbes_Cover.jpg.jpg"
        }
      },
      {
        "id": "luca-schmales-gesicht-auf-blau",
        "artistId": "luca",
        "title": "Schmales Gesicht auf blau",
        "year": 2025,
        "medium": "Acryl auf Papier",
        "widthCm": 60,
        "heightCm": 75,
        "priceEur": 675,
        "category": "paper",
        "status": "available",
        "zoneId": 0,
        "images": {
          "texture": "/artist/luca/images/02_Schmales_Gesicht_auf_blau.jpg.jpg",
          "full": "/artist/luca/images/02_Schmales_Gesicht_auf_blau.jpg.jpg",
          "thumb": "/artist/luca/images/02_Schmales_Gesicht_auf_blau.jpg.jpg"
        }
      },
      {
        "id": "luca-figuren-in-der-masse",
        "artistId": "luca",
        "title": "Figuren in der Masse",
        "year": 2025,
        "medium": "Acryl auf Papier",
        "widthCm": 59,
        "heightCm": 99,
        "priceEur": 630,
        "category": "paper",
        "status": "available",
        "zoneId": 0,
        "images": {
          "texture": "/artist/luca/images/03_Figuren_in_der_Masse.jpg.jpg",
          "full": "/artist/luca/images/03_Figuren_in_der_Masse.jpg.jpg",
          "thumb": "/artist/luca/images/03_Figuren_in_der_Masse.jpg.jpg"
        }
      },
      {
        "id": "luca-vorhang",
        "artistId": "luca",
        "title": "Vorhang",
        "year": 2026,
        "medium": "Acryl auf Holz",
        "widthCm": 157,
        "heightCm": 140,
        "priceEur": 700,
        "category": "other",
        "status": "available",
        "zoneId": 0,
        "images": {
          "texture": "/artist/luca/images/04_Vorhang.jpg.jpg",
          "full": "/artist/luca/images/04_Vorhang.jpg.jpg",
          "thumb": "/artist/luca/images/04_Vorhang.jpg.jpg"
        }
      },
      {
        "id": "luca-expressreihe-1",
        "artistId": "luca",
        "title": "Expressreihe 1",
        "year": 2026,
        "medium": "Acryl auf Papier",
        "widthCm": 30,
        "heightCm": 38,
        "priceEur": 350,
        "category": "paper",
        "status": "available",
        "zoneId": 0,
        "images": {
          "texture": "/artist/luca/images/05_Expressreihe_1.jpg.jpg",
          "full": "/artist/luca/images/05_Expressreihe_1.jpg.jpg",
          "thumb": "/artist/luca/images/05_Expressreihe_1.jpg.jpg"
        }
      },
      {
        "id": "luca-expressreihe-2",
        "artistId": "luca",
        "title": "Expressreihe 2",
        "year": 2026,
        "medium": "Acryl auf Papier",
        "widthCm": 30,
        "heightCm": 38,
        "priceEur": 350,
        "category": "paper",
        "status": "available",
        "zoneId": 0,
        "images": {
          "texture": "/artist/luca/images/06_Expressreihe_2.jpg.jpg",
          "full": "/artist/luca/images/06_Expressreihe_2.jpg.jpg",
          "thumb": "/artist/luca/images/06_Expressreihe_2.jpg.jpg"
        }
      },
      {
        "id": "luca-homunkulus",
        "artistId": "luca",
        "title": "Homunkulus",
        "year": 2026,
        "medium": "Acryl auf Papier",
        "widthCm": 60,
        "heightCm": 75,
        "priceEur": 620,
        "category": "paper",
        "status": "available",
        "zoneId": 0,
        "images": {
          "texture": "/artist/luca/images/07_Homunkulus.jpg.jpg",
          "full": "/artist/luca/images/07_Homunkulus.jpg.jpg",
          "thumb": "/artist/luca/images/07_Homunkulus.jpg.jpg"
        }
      },
      {
        "id": "luca-wiederkehr",
        "artistId": "luca",
        "title": "Wiederkehr",
        "year": 2026,
        "medium": "Acryl auf Papier",
        "widthCm": 30,
        "heightCm": 38,
        "priceEur": 350,
        "category": "paper",
        "status": "available",
        "zoneId": 0,
        "images": {
          "texture": "/artist/luca/images/08_Wiederkehr.jpg.jpg",
          "full": "/artist/luca/images/08_Wiederkehr.jpg.jpg",
          "thumb": "/artist/luca/images/08_Wiederkehr.jpg.jpg"
        }
      },
      {
        "id": "luca-portrait-1",
        "artistId": "luca",
        "title": "Portrait",
        "category": "other",
        "status": "available",
        "zoneId": 0,
        "images": {
          "texture": "/artist/luca/images/Künstlerpic.jpeg",
          "full": "/artist/luca/images/Künstlerpic.jpeg",
          "thumb": "/artist/luca/images/Künstlerpic.jpeg"
        }
      },
      {
        "id": "luca-portrait-2",
        "artistId": "luca",
        "title": "Portrait 2",
        "category": "other",
        "status": "available",
        "zoneId": 0,
        "images": {
          "texture": "/artist/luca/images/fit inspiration für avatar.jpeg",
          "full": "/artist/luca/images/fit inspiration für avatar.jpeg",
          "thumb": "/artist/luca/images/fit inspiration für avatar.jpeg"
        }
      }
    ]
  },
  {
    "artist": {
      "id": "example-room",
      "slug": "example-room",
      "name": "Example Room",
      "bioMarkdown": "Leerer Beispielraum fuer Kuenstlerbewerbungen.",
      "contact": {},
      "links": [],
      "exhibitions": []
    },
    "rooms": [
      {
        "id": "example-room",
        "title": "Example Room",
        "theme": "modern",
        "length": 24,
        "width": 24,
        "height": 7.4,
        "accentColor": "#7fc9ff",
        "categoryFilter": [
          "canvas_large",
          "canvas_small",
          "paper",
          "other"
        ],
        "maxArtworks": 0,
        "wallTexture": "/backgrounds/room1-a.jpg",
        "wallTextureAlt": "/backgrounds/room1-b.jpg",
        "floorTexture": "/backgrounds/room1-floor.jpg",
        "ceilingTexture": "/backgrounds/nacht-decke.png"
      }
    ],
    "artworks": []
  }
];

