/* eslint-disable */
// This file is generated by scripts/import_artworks.py from data/catalog/artworks.csv
// Do not edit by hand.

import type { ArtworkOverride } from "@/content/artworks.overrides";

export const generatedOverridesAtIso = "2026-02-13T11:59:23.719740+00:00";

export const artworkOverrides: Record<string, ArtworkOverride> = {
  "canvas-large-bier-bass-belanglosikeit": {
    "title": "Bier Bass Belanglosikeit",
    "year": 2022,
    "widthCm": 70,
    "heightCm": 100,
    "status": "available",
    "priceEur": 700.0,
    "artistId": "felix",
    "category": "canvas_large"
  },
  "canvas-large-chaos-im-komando-zentrum": {
    "title": "Chaos im Komando zentrum",
    "year": 2023,
    "widthCm": 80,
    "heightCm": 100,
    "status": "available",
    "priceEur": 1600.0,
    "artistId": "felix",
    "category": "canvas_large"
  },
  "canvas-large-chaosin-comandozentrum": {
    "title": "chaosin Comandozentrum",
    "year": 2023,
    "widthCm": 80,
    "heightCm": 100,
    "status": "available",
    "priceEur": 1600.0,
    "artistId": "felix",
    "category": "canvas_large"
  },
  "canvas-large-experiment-sterotyp": {
    "title": "Experiment sterotyp",
    "year": 2023,
    "widthCm": 160,
    "heightCm": 100,
    "status": "available",
    "priceEur": 1200.0,
    "artistId": "felix",
    "category": "canvas_large"
  },
  "canvas-large-expetition-zur-entspannung": {
    "title": "expetition zur Entspannung",
    "year": 2023,
    "widthCm": 160,
    "heightCm": 100,
    "status": "available",
    "priceEur": 2400.0,
    "artistId": "felix",
    "category": "canvas_large"
  },
  "canvas-large-felix-iplfing-wegeundtueren": {
    "title": "Felix Iplfing wegeundtüren",
    "year": 2022,
    "widthCm": 75,
    "heightCm": 115,
    "status": "not_for_sale",
    "artistId": "felix",
    "category": "canvas_large"
  },
  "canvas-large-freunde": {
    "title": "freunde",
    "year": 2024,
    "widthCm": 160,
    "heightCm": 100,
    "status": "available",
    "priceEur": 1900.0,
    "artistId": "felix",
    "category": "canvas_large"
  },
  "canvas-large-gangster": {
    "title": "Gangster",
    "year": 2022,
    "widthCm": 100,
    "heightCm": 70,
    "status": "available",
    "priceEur": 700.0,
    "artistId": "felix",
    "category": "canvas_large"
  },
  "canvas-large-m6-live-painting": {
    "title": "M6 Live Painting",
    "year": 2023,
    "widthCm": 160,
    "heightCm": 100,
    "status": "not_for_sale",
    "artistId": "felix",
    "category": "canvas_large"
  },
  "canvas-large-u-bahn": {
    "title": "u bahn",
    "year": 2022,
    "widthCm": 75,
    "heightCm": 115,
    "status": "available",
    "priceEur": 1450.0,
    "artistId": "felix",
    "category": "canvas_large"
  },
  "canvas-large-ungleichgewicht": {
    "title": "Ungleichgewicht",
    "year": 2022,
    "widthCm": 115,
    "heightCm": 75,
    "status": "available",
    "priceEur": 1670.0,
    "artistId": "felix",
    "category": "canvas_large"
  },
  "canvas-large-welches-spiel": {
    "title": "welches Spiel",
    "year": 2022,
    "widthCm": 80,
    "heightCm": 100,
    "status": "not_for_sale",
    "artistId": "felix",
    "category": "canvas_large"
  },
  "canvas-large-zeit-rieselt": {
    "title": "Zeit rieselt",
    "year": 2023,
    "widthCm": 160,
    "heightCm": 100,
    "status": "available",
    "priceEur": 3470.0,
    "artistId": "felix",
    "category": "canvas_large"
  },
  "canvas-small-amrunden-tisch": {
    "title": "amrunden Tisch",
    "year": 2023,
    "widthCm": 40,
    "heightCm": 50,
    "status": "not_for_sale",
    "artistId": "felix",
    "category": "canvas_small"
  },
  "canvas-small-b-adestrndbueroo": {
    "title": "B Adestrndbüroo",
    "year": 2023,
    "widthCm": 60,
    "heightCm": 50,
    "status": "not_for_sale",
    "artistId": "felix",
    "category": "canvas_small"
  },
  "canvas-small-bild-mercedes": {
    "title": "Bild Mercedes",
    "year": 2023,
    "widthCm": 70,
    "heightCm": 50,
    "status": "available",
    "priceEur": 1200.0,
    "artistId": "felix",
    "category": "canvas_small"
  },
  "canvas-small-bis-zum-letzten-tropfen": {
    "title": "bis Zum Letzten Tropfen",
    "year": 2022,
    "widthCm": 60,
    "heightCm": 50,
    "status": "available",
    "priceEur": 700.0,
    "artistId": "felix",
    "category": "canvas_small"
  },
  "canvas-small-blondine-mit-smartphone": {
    "title": "Blondine Mit Smartphone",
    "year": 2022,
    "widthCm": 40,
    "heightCm": 50,
    "status": "not_for_sale",
    "artistId": "felix",
    "category": "canvas_small"
  },
  "canvas-small-buissnes-as-usuall": {
    "title": "buissnes as usuall",
    "year": 2023,
    "widthCm": 60,
    "heightCm": 50,
    "status": "available",
    "priceEur": 1200.0,
    "artistId": "felix",
    "category": "canvas_small"
  },
  "canvas-small-data-down": {
    "title": "Data Down",
    "year": 2022,
    "widthCm": 40,
    "heightCm": 50,
    "status": "available",
    "priceEur": 600.0,
    "artistId": "felix",
    "category": "canvas_small"
  },
  "canvas-small-der-rote-luftballon": {
    "title": "der rote luftballon",
    "year": 2022,
    "widthCm": 40,
    "heightCm": 50,
    "status": "available",
    "priceEur": 600.0,
    "artistId": "felix",
    "category": "canvas_small"
  },
  "canvas-small-gefangen-im-geist": {
    "title": "gefangen im Geist",
    "year": 2023,
    "widthCm": 50,
    "heightCm": 50,
    "status": "available",
    "priceEur": 700.0,
    "artistId": "felix",
    "category": "canvas_small"
  },
  "canvas-small-haltfest-renn-weg": {
    "title": "haltfest Renn Weg",
    "year": 2022,
    "widthCm": 40,
    "heightCm": 50,
    "status": "available",
    "priceEur": 620.0,
    "artistId": "felix",
    "category": "canvas_small"
  },
  "canvas-small-hedonistische-helden": {
    "title": "Hedonistische Helden",
    "year": 2022,
    "widthCm": 70,
    "heightCm": 50,
    "status": "not_for_sale",
    "artistId": "felix",
    "category": "canvas_small"
  },
  "canvas-small-humania-i-ijpg": {
    "title": "Humania I Ijpg",
    "year": 2021,
    "widthCm": 68,
    "heightCm": 48,
    "status": "available",
    "priceEur": 1400.0,
    "artistId": "felix",
    "category": "canvas_small"
  },
  "canvas-small-raus-aus-dem-dorf": {
    "title": "raus aus dem dorf",
    "year": 2021,
    "widthCm": 50,
    "heightCm": 40,
    "status": "available",
    "priceEur": 400.0,
    "artistId": "felix",
    "category": "canvas_small"
  },
  "canvas-small-swanestirn": {
    "title": "swanestirn",
    "year": 2021,
    "widthCm": 30,
    "heightCm": 20,
    "status": "available",
    "priceEur": 400.0,
    "artistId": "felix",
    "category": "canvas_small"
  },
  "canvas-small-was-fuer-benz": {
    "title": "was Für Benz",
    "year": 2023,
    "widthCm": 50,
    "heightCm": 60,
    "status": "available",
    "priceEur": 1200.0,
    "artistId": "felix",
    "category": "canvas_small"
  },
  "canvas-small-wohin": {
    "title": "Wohin?",
    "year": 2023,
    "widthCm": 50,
    "heightCm": 60,
    "status": "available",
    "priceEur": 840.0,
    "artistId": "felix",
    "category": "canvas_small"
  },
  "canvas-small-ziellos-auf-schienen": {
    "title": "Ziellos Auf Schienen",
    "year": 2022,
    "widthCm": 50,
    "heightCm": 70,
    "status": "available",
    "priceEur": 600.0,
    "artistId": "felix",
    "category": "canvas_small"
  },
  "canvas-small-zittern-im-zwielicht": {
    "title": "Zittern im zwielicht",
    "year": 2022,
    "widthCm": 60,
    "heightCm": 75,
    "status": "available",
    "priceEur": 750.0,
    "artistId": "felix",
    "category": "canvas_small"
  },
  "other-zeit-rieselt-shirtforne": {
    "title": "Zeit rieselt shirtforne",
    "year": 2023,
    "status": "available",
    "artistId": "felix",
    "category": "other"
  },
  "paper-akt-auf-blau": {
    "title": "Akt auf Blau",
    "year": 2023,
    "status": "available",
    "priceEur": 450.0,
    "artistId": "felix",
    "category": "paper"
  },
  "paper-alles-klamauk": {
    "title": "alles Klamauk",
    "year": 2022,
    "status": "available",
    "priceEur": 380.0,
    "artistId": "felix",
    "category": "paper"
  },
  "paper-augen": {
    "title": "augen",
    "year": 2021,
    "status": "available",
    "priceEur": 350.0,
    "artistId": "felix",
    "category": "paper"
  },
  "paper-auslauf": {
    "title": "Auslauf",
    "year": 2021,
    "status": "available",
    "priceEur": 560.0,
    "artistId": "felix",
    "category": "paper"
  },
  "paper-bmas-s4": {
    "title": "BMAS S4",
    "year": 2023,
    "status": "available",
    "priceEur": 450.0,
    "artistId": "felix",
    "category": "paper"
  },
  "paper-die-bande": {
    "title": "Die Bande",
    "year": 2022,
    "status": "not_for_sale",
    "artistId": "felix",
    "category": "paper"
  },
  "paper-im-flus-am-flusss": {
    "title": "im flus am flusss",
    "year": 2022,
    "status": "available",
    "priceEur": 400.0,
    "artistId": "felix",
    "category": "paper"
  },
  "paper-komposition1": {
    "title": "komposition1",
    "year": 2021,
    "status": "available",
    "priceEur": 250.0,
    "artistId": "felix",
    "category": "paper"
  },
  "paper-komposition2": {
    "title": "komposition2",
    "year": 2021,
    "status": "available",
    "priceEur": 250.0,
    "artistId": "felix",
    "category": "paper"
  },
  "paper-nazisim-jkh": {
    "title": "Nazis,im JKH",
    "year": 2023,
    "status": "available",
    "priceEur": 250.0,
    "artistId": "felix",
    "category": "paper"
  },
  "paper-slepplesnights": {
    "title": "slepplesnights",
    "year": 2021,
    "status": "available",
    "priceEur": 250.0,
    "artistId": "felix",
    "category": "paper"
  },
  "paper-taenzer": {
    "title": "taenzer",
    "year": 2021,
    "status": "available",
    "priceEur": 250.0,
    "artistId": "felix",
    "category": "paper"
  },
  "paper-tick-tack-tip": {
    "title": "Tick Tack Tip",
    "year": 2021,
    "status": "available",
    "priceEur": 250.0,
    "artistId": "felix",
    "category": "paper"
  },
  "paper-vulkan": {
    "title": "vulkan",
    "year": 2021,
    "status": "available",
    "priceEur": 250.0,
    "artistId": "felix",
    "category": "paper"
  }
}
;
