/* eslint-disable */
// This file is generated by scripts/import_artworks.py
// Do not edit by hand; use `artworks.overrides.ts` for manual changes.

import type { Artwork } from "@/content/types";

export const generatedAtIso = "2026-02-13T11:59:23.714782+00:00";

export const generatedArtworks: Artwork[] = [
  {
    "id": "canvas-large-bier-bass-belanglosikeit",
    "artistId": "felix",
    "title": "Bier Bass Belanglosikeit",
    "widthCm": 70,
    "heightCm": 100,
    "aspect": 1.422792,
    "category": "canvas_large",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#686159",
    "images": {
      "texture": "/artworks/canvas-large-bier-bass-belanglosikeit/texture.webp",
      "full": "/artworks/canvas-large-bier-bass-belanglosikeit/full.webp",
      "thumb": "/artworks/canvas-large-bier-bass-belanglosikeit/thumb.webp"
    }
  },
  {
    "id": "canvas-large-chaos-im-komando-zentrum",
    "artistId": "felix",
    "title": "Chaos im Komando zentrum",
    "aspect": 1.273732,
    "category": "canvas_large",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#67645c",
    "images": {
      "texture": "/artworks/canvas-large-chaos-im-komando-zentrum/texture.webp",
      "full": "/artworks/canvas-large-chaos-im-komando-zentrum/full.webp",
      "thumb": "/artworks/canvas-large-chaos-im-komando-zentrum/thumb.webp"
    }
  },
  {
    "id": "canvas-large-chaosin-comandozentrum",
    "artistId": "felix",
    "title": "chaosin Comandozentrum",
    "aspect": 1.251878,
    "category": "canvas_large",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#6f6c64",
    "images": {
      "texture": "/artworks/canvas-large-chaosin-comandozentrum/texture.webp",
      "full": "/artworks/canvas-large-chaosin-comandozentrum/full.webp",
      "thumb": "/artworks/canvas-large-chaosin-comandozentrum/thumb.webp"
    }
  },
  {
    "id": "canvas-large-experiment-sterotyp",
    "artistId": "felix",
    "title": "Experiment sterotyp",
    "aspect": 1.581623,
    "category": "canvas_large",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#705f5c",
    "images": {
      "texture": "/artworks/canvas-large-experiment-sterotyp/texture.webp",
      "full": "/artworks/canvas-large-experiment-sterotyp/full.webp",
      "thumb": "/artworks/canvas-large-experiment-sterotyp/thumb.webp"
    }
  },
  {
    "id": "canvas-large-expetition-zur-entspannung",
    "artistId": "felix",
    "title": "expetition zur Entspannung",
    "aspect": 1.541754,
    "category": "canvas_large",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#6c625b",
    "images": {
      "texture": "/artworks/canvas-large-expetition-zur-entspannung/texture.webp",
      "full": "/artworks/canvas-large-expetition-zur-entspannung/full.webp",
      "thumb": "/artworks/canvas-large-expetition-zur-entspannung/thumb.webp"
    }
  },
  {
    "id": "canvas-large-felix-iplfing-wegeundtueren",
    "artistId": "felix",
    "title": "Felix Iplfing wegeundtüren",
    "widthCm": 75,
    "heightCm": 115,
    "aspect": 0.647907,
    "category": "canvas_large",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#82624d",
    "images": {
      "texture": "/artworks/canvas-large-felix-iplfing-wegeundtueren/texture.webp",
      "full": "/artworks/canvas-large-felix-iplfing-wegeundtueren/full.webp",
      "thumb": "/artworks/canvas-large-felix-iplfing-wegeundtueren/thumb.webp"
    }
  },
  {
    "id": "canvas-large-freunde",
    "artistId": "felix",
    "title": "freunde",
    "aspect": 1.301695,
    "category": "canvas_large",
    "status": "available",
    "zoneId": 2,
    "dominantColor": "#4c4a57",
    "images": {
      "texture": "/artworks/canvas-large-freunde/texture.webp",
      "full": "/artworks/canvas-large-freunde/full.webp",
      "thumb": "/artworks/canvas-large-freunde/thumb.webp"
    }
  },
  {
    "id": "canvas-large-gangster",
    "artistId": "felix",
    "title": "Gangster",
    "aspect": 1.434978,
    "category": "canvas_large",
    "status": "available",
    "zoneId": 2,
    "dominantColor": "#723e61",
    "images": {
      "texture": "/artworks/canvas-large-gangster/texture.webp",
      "full": "/artworks/canvas-large-gangster/full.webp",
      "thumb": "/artworks/canvas-large-gangster/thumb.webp"
    }
  },
  {
    "id": "canvas-large-m6-live-painting",
    "artistId": "felix",
    "title": "M6 Live Painting",
    "aspect": 1.268085,
    "category": "canvas_large",
    "status": "available",
    "zoneId": 2,
    "dominantColor": "#544c45",
    "images": {
      "texture": "/artworks/canvas-large-m6-live-painting/texture.webp",
      "full": "/artworks/canvas-large-m6-live-painting/full.webp",
      "thumb": "/artworks/canvas-large-m6-live-painting/thumb.webp"
    }
  },
  {
    "id": "canvas-large-u-bahn",
    "artistId": "felix",
    "title": "u bahn",
    "aspect": 0.656771,
    "category": "canvas_large",
    "status": "available",
    "zoneId": 1,
    "dominantColor": "#6e8a9d",
    "images": {
      "texture": "/artworks/canvas-large-u-bahn/texture.webp",
      "full": "/artworks/canvas-large-u-bahn/full.webp",
      "thumb": "/artworks/canvas-large-u-bahn/thumb.webp"
    }
  },
  {
    "id": "canvas-large-ungleichgewicht",
    "artistId": "felix",
    "title": "Ungleichgewicht",
    "widthCm": 115,
    "heightCm": 75,
    "aspect": 1.560717,
    "category": "canvas_large",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#807060",
    "images": {
      "texture": "/artworks/canvas-large-ungleichgewicht/texture.webp",
      "full": "/artworks/canvas-large-ungleichgewicht/full.webp",
      "thumb": "/artworks/canvas-large-ungleichgewicht/thumb.webp"
    }
  },
  {
    "id": "canvas-large-welches-spiel",
    "artistId": "felix",
    "title": "welches Spiel",
    "widthCm": 80,
    "heightCm": 100,
    "aspect": 1.266506,
    "category": "canvas_large",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#776e65",
    "images": {
      "texture": "/artworks/canvas-large-welches-spiel/texture.webp",
      "full": "/artworks/canvas-large-welches-spiel/full.webp",
      "thumb": "/artworks/canvas-large-welches-spiel/thumb.webp"
    }
  },
  {
    "id": "canvas-large-zeit-rieselt",
    "artistId": "felix",
    "title": "Zeit rieselt",
    "aspect": 1.451278,
    "category": "canvas_large",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#8d725b",
    "images": {
      "texture": "/artworks/canvas-large-zeit-rieselt/texture.webp",
      "full": "/artworks/canvas-large-zeit-rieselt/full.webp",
      "thumb": "/artworks/canvas-large-zeit-rieselt/thumb.webp"
    }
  },
  {
    "id": "canvas-small-amrunden-tisch",
    "artistId": "felix",
    "title": "amrunden Tisch",
    "aspect": 1.266472,
    "category": "canvas_small",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#655252",
    "images": {
      "texture": "/artworks/canvas-small-amrunden-tisch/texture.webp",
      "full": "/artworks/canvas-small-amrunden-tisch/full.webp",
      "thumb": "/artworks/canvas-small-amrunden-tisch/thumb.webp"
    }
  },
  {
    "id": "canvas-small-b-adestrndbueroo",
    "artistId": "felix",
    "title": "B Adestrndbüroo",
    "aspect": 1.188164,
    "category": "canvas_small",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#6f6766",
    "images": {
      "texture": "/artworks/canvas-small-b-adestrndbueroo/texture.webp",
      "full": "/artworks/canvas-small-b-adestrndbueroo/full.webp",
      "thumb": "/artworks/canvas-small-b-adestrndbueroo/thumb.webp"
    }
  },
  {
    "id": "canvas-small-bild-mercedes",
    "artistId": "felix",
    "title": "Bild Mercedes",
    "year": 2023,
    "aspect": 1.422611,
    "category": "canvas_small",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#6f7475",
    "images": {
      "texture": "/artworks/canvas-small-bild-mercedes/texture.webp",
      "full": "/artworks/canvas-small-bild-mercedes/full.webp",
      "thumb": "/artworks/canvas-small-bild-mercedes/thumb.webp"
    }
  },
  {
    "id": "canvas-small-bis-zum-letzten-tropfen",
    "artistId": "felix",
    "title": "bis Zum Letzten Tropfen",
    "widthCm": 50,
    "heightCm": 60,
    "aspect": 1.191692,
    "category": "canvas_small",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#71625a",
    "images": {
      "texture": "/artworks/canvas-small-bis-zum-letzten-tropfen/texture.webp",
      "full": "/artworks/canvas-small-bis-zum-letzten-tropfen/full.webp",
      "thumb": "/artworks/canvas-small-bis-zum-letzten-tropfen/thumb.webp"
    }
  },
  {
    "id": "canvas-small-blondine-mit-smartphone",
    "artistId": "felix",
    "title": "Blondine Mit Smartphone",
    "aspect": 0.857292,
    "category": "canvas_small",
    "status": "available",
    "zoneId": 2,
    "dominantColor": "#33716f",
    "images": {
      "texture": "/artworks/canvas-small-blondine-mit-smartphone/texture.webp",
      "full": "/artworks/canvas-small-blondine-mit-smartphone/full.webp",
      "thumb": "/artworks/canvas-small-blondine-mit-smartphone/thumb.webp"
    }
  },
  {
    "id": "canvas-small-buissnes-as-usuall",
    "artistId": "felix",
    "title": "buissnes as usuall",
    "aspect": 1.206182,
    "category": "canvas_small",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#625554",
    "images": {
      "texture": "/artworks/canvas-small-buissnes-as-usuall/texture.webp",
      "full": "/artworks/canvas-small-buissnes-as-usuall/full.webp",
      "thumb": "/artworks/canvas-small-buissnes-as-usuall/thumb.webp"
    }
  },
  {
    "id": "canvas-small-data-down",
    "artistId": "felix",
    "title": "Data Down",
    "widthCm": 40,
    "heightCm": 50,
    "aspect": 0.796136,
    "category": "canvas_small",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#756041",
    "images": {
      "texture": "/artworks/canvas-small-data-down/texture.webp",
      "full": "/artworks/canvas-small-data-down/full.webp",
      "thumb": "/artworks/canvas-small-data-down/thumb.webp"
    }
  },
  {
    "id": "canvas-small-der-rote-luftballon",
    "artistId": "felix",
    "title": "der rote luftballon",
    "aspect": 0.741211,
    "category": "canvas_small",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#856d70",
    "images": {
      "texture": "/artworks/canvas-small-der-rote-luftballon/texture.webp",
      "full": "/artworks/canvas-small-der-rote-luftballon/full.webp",
      "thumb": "/artworks/canvas-small-der-rote-luftballon/thumb.webp"
    }
  },
  {
    "id": "canvas-small-gefangen-im-geist",
    "artistId": "felix",
    "title": "gefangen im Geist",
    "aspect": 0.988001,
    "category": "canvas_small",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#705744",
    "images": {
      "texture": "/artworks/canvas-small-gefangen-im-geist/texture.webp",
      "full": "/artworks/canvas-small-gefangen-im-geist/full.webp",
      "thumb": "/artworks/canvas-small-gefangen-im-geist/thumb.webp"
    }
  },
  {
    "id": "canvas-small-haltfest-renn-weg",
    "artistId": "felix",
    "title": "haltfest Renn Weg",
    "widthCm": 40,
    "heightCm": 50,
    "aspect": 0.799527,
    "category": "canvas_small",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#886956",
    "images": {
      "texture": "/artworks/canvas-small-haltfest-renn-weg/texture.webp",
      "full": "/artworks/canvas-small-haltfest-renn-weg/full.webp",
      "thumb": "/artworks/canvas-small-haltfest-renn-weg/thumb.webp"
    }
  },
  {
    "id": "canvas-small-hedonistische-helden",
    "artistId": "felix",
    "title": "Hedonistische Helden",
    "aspect": 1.407307,
    "category": "canvas_small",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#645e5c",
    "images": {
      "texture": "/artworks/canvas-small-hedonistische-helden/texture.webp",
      "full": "/artworks/canvas-small-hedonistische-helden/full.webp",
      "thumb": "/artworks/canvas-small-hedonistische-helden/thumb.webp"
    }
  },
  {
    "id": "canvas-small-humania-i-ijpg",
    "artistId": "felix",
    "title": "Humania I Ijpg",
    "aspect": 1.214436,
    "category": "canvas_small",
    "status": "available",
    "zoneId": 1,
    "dominantColor": "#a39182",
    "images": {
      "texture": "/artworks/canvas-small-humania-i-ijpg/texture.webp",
      "full": "/artworks/canvas-small-humania-i-ijpg/full.webp",
      "thumb": "/artworks/canvas-small-humania-i-ijpg/thumb.webp"
    }
  },
  {
    "id": "canvas-small-raus-aus-dem-dorf",
    "artistId": "felix",
    "title": "raus aus dem dorf",
    "aspect": 1.245944,
    "category": "canvas_small",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#6c6d6a",
    "images": {
      "texture": "/artworks/canvas-small-raus-aus-dem-dorf/texture.webp",
      "full": "/artworks/canvas-small-raus-aus-dem-dorf/full.webp",
      "thumb": "/artworks/canvas-small-raus-aus-dem-dorf/thumb.webp"
    }
  },
  {
    "id": "canvas-small-swanestirn",
    "artistId": "felix",
    "title": "swanestirn",
    "aspect": 1.384615,
    "category": "canvas_small",
    "status": "available",
    "zoneId": 1,
    "dominantColor": "#7b8081",
    "images": {
      "texture": "/artworks/canvas-small-swanestirn/texture.webp",
      "full": "/artworks/canvas-small-swanestirn/full.webp",
      "thumb": "/artworks/canvas-small-swanestirn/thumb.webp"
    }
  },
  {
    "id": "canvas-small-was-fuer-benz",
    "artistId": "felix",
    "title": "was Für Benz",
    "aspect": 1.407291,
    "category": "canvas_small",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#66635d",
    "images": {
      "texture": "/artworks/canvas-small-was-fuer-benz/texture.webp",
      "full": "/artworks/canvas-small-was-fuer-benz/full.webp",
      "thumb": "/artworks/canvas-small-was-fuer-benz/thumb.webp"
    }
  },
  {
    "id": "canvas-small-wohin",
    "artistId": "felix",
    "title": "Wohin?",
    "widthCm": 50,
    "heightCm": 60,
    "aspect": 1.196878,
    "category": "canvas_small",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#896d57",
    "images": {
      "texture": "/artworks/canvas-small-wohin/texture.webp",
      "full": "/artworks/canvas-small-wohin/full.webp",
      "thumb": "/artworks/canvas-small-wohin/thumb.webp"
    }
  },
  {
    "id": "canvas-small-ziellos-auf-schienen",
    "artistId": "felix",
    "title": "Ziellos Auf Schienen",
    "aspect": 0.840625,
    "category": "canvas_small",
    "status": "available",
    "zoneId": 2,
    "dominantColor": "#487895",
    "images": {
      "texture": "/artworks/canvas-small-ziellos-auf-schienen/texture.webp",
      "full": "/artworks/canvas-small-ziellos-auf-schienen/full.webp",
      "thumb": "/artworks/canvas-small-ziellos-auf-schienen/thumb.webp"
    }
  },
  {
    "id": "canvas-small-zittern-im-zwielicht",
    "artistId": "felix",
    "title": "Zittern im zwielicht",
    "widthCm": 60,
    "heightCm": 75,
    "aspect": 1.307902,
    "category": "canvas_small",
    "status": "available",
    "zoneId": 2,
    "dominantColor": "#4c5974",
    "images": {
      "texture": "/artworks/canvas-small-zittern-im-zwielicht/texture.webp",
      "full": "/artworks/canvas-small-zittern-im-zwielicht/full.webp",
      "thumb": "/artworks/canvas-small-zittern-im-zwielicht/thumb.webp"
    }
  },
  {
    "id": "other-atelier-impression",
    "artistId": "felix",
    "title": "atelier impression",
    "aspect": 0.75,
    "category": "other",
    "status": "available",
    "zoneId": 1,
    "dominantColor": "#8d827b",
    "images": {
      "texture": "/artworks/other-atelier-impression/texture.webp",
      "full": "/artworks/other-atelier-impression/full.webp",
      "thumb": "/artworks/other-atelier-impression/thumb.webp"
    }
  },
  {
    "id": "other-portrait-b",
    "artistId": "felix",
    "title": "portrait b",
    "aspect": 0.75,
    "category": "other",
    "status": "available",
    "zoneId": 1,
    "dominantColor": "#a49b92",
    "images": {
      "texture": "/artworks/other-portrait-b/texture.webp",
      "full": "/artworks/other-portrait-b/full.webp",
      "thumb": "/artworks/other-portrait-b/thumb.webp"
    }
  },
  {
    "id": "other-portraita",
    "artistId": "felix",
    "title": "portrait.a",
    "aspect": 0.75,
    "category": "other",
    "status": "available",
    "zoneId": 1,
    "dominantColor": "#9b9388",
    "images": {
      "texture": "/artworks/other-portraita/texture.webp",
      "full": "/artworks/other-portraita/full.webp",
      "thumb": "/artworks/other-portraita/thumb.webp"
    }
  },
  {
    "id": "other-portraitatelier",
    "artistId": "felix",
    "title": "portrait.atelier",
    "aspect": 0.75,
    "category": "other",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#7d7a6f",
    "images": {
      "texture": "/artworks/other-portraitatelier/texture.webp",
      "full": "/artworks/other-portraitatelier/full.webp",
      "thumb": "/artworks/other-portraitatelier/thumb.webp"
    }
  },
  {
    "id": "paper-akt-auf-blau",
    "artistId": "felix",
    "title": "Akt auf Blau",
    "aspect": 0.708503,
    "category": "paper",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#756854",
    "images": {
      "texture": "/artworks/paper-akt-auf-blau/texture.webp",
      "full": "/artworks/paper-akt-auf-blau/full.webp",
      "thumb": "/artworks/paper-akt-auf-blau/thumb.webp"
    }
  },
  {
    "id": "paper-alles-klamauk",
    "artistId": "felix",
    "title": "alles Klamauk",
    "aspect": 0.933449,
    "category": "paper",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#7b585a",
    "images": {
      "texture": "/artworks/paper-alles-klamauk/texture.webp",
      "full": "/artworks/paper-alles-klamauk/full.webp",
      "thumb": "/artworks/paper-alles-klamauk/thumb.webp"
    }
  },
  {
    "id": "paper-augen",
    "artistId": "felix",
    "title": "augen",
    "aspect": 1.514505,
    "category": "paper",
    "status": "available",
    "zoneId": 1,
    "dominantColor": "#898288",
    "images": {
      "texture": "/artworks/paper-augen/texture.webp",
      "full": "/artworks/paper-augen/full.webp",
      "thumb": "/artworks/paper-augen/thumb.webp"
    }
  },
  {
    "id": "paper-auslauf",
    "artistId": "felix",
    "title": "Auslauf",
    "aspect": 0.701189,
    "category": "paper",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#837666",
    "images": {
      "texture": "/artworks/paper-auslauf/texture.webp",
      "full": "/artworks/paper-auslauf/full.webp",
      "thumb": "/artworks/paper-auslauf/thumb.webp"
    }
  },
  {
    "id": "paper-bmas-s4",
    "artistId": "felix",
    "title": "BMAS S4",
    "aspect": 1.383385,
    "category": "paper",
    "status": "available",
    "zoneId": 1,
    "dominantColor": "#988971",
    "images": {
      "texture": "/artworks/paper-bmas-s4/texture.webp",
      "full": "/artworks/paper-bmas-s4/full.webp",
      "thumb": "/artworks/paper-bmas-s4/thumb.webp"
    }
  },
  {
    "id": "paper-der-hoffnungs-haenker",
    "artistId": "felix",
    "title": "der Hoffnungs Hänker",
    "aspect": 1.007329,
    "category": "paper",
    "status": "available",
    "zoneId": 1,
    "dominantColor": "#9a918e",
    "images": {
      "texture": "/artworks/paper-der-hoffnungs-haenker/texture.webp",
      "full": "/artworks/paper-der-hoffnungs-haenker/full.webp",
      "thumb": "/artworks/paper-der-hoffnungs-haenker/thumb.webp"
    }
  },
  {
    "id": "paper-die-bande",
    "artistId": "felix",
    "title": "Die Bande",
    "aspect": 1.381295,
    "category": "paper",
    "status": "available",
    "zoneId": 2,
    "dominantColor": "#3a5877",
    "images": {
      "texture": "/artworks/paper-die-bande/texture.webp",
      "full": "/artworks/paper-die-bande/full.webp",
      "thumb": "/artworks/paper-die-bande/thumb.webp"
    }
  },
  {
    "id": "paper-im-flus-am-flusss",
    "artistId": "felix",
    "title": "im flus am flusss",
    "aspect": 1.468424,
    "category": "paper",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#807a72",
    "images": {
      "texture": "/artworks/paper-im-flus-am-flusss/texture.webp",
      "full": "/artworks/paper-im-flus-am-flusss/full.webp",
      "thumb": "/artworks/paper-im-flus-am-flusss/thumb.webp"
    }
  },
  {
    "id": "paper-komposition1",
    "artistId": "felix",
    "title": "komposition1",
    "aspect": 1.559594,
    "category": "paper",
    "status": "available",
    "zoneId": 1,
    "dominantColor": "#7a8ab1",
    "images": {
      "texture": "/artworks/paper-komposition1/texture.webp",
      "full": "/artworks/paper-komposition1/full.webp",
      "thumb": "/artworks/paper-komposition1/thumb.webp"
    }
  },
  {
    "id": "paper-komposition2",
    "artistId": "felix",
    "title": "komposition2",
    "aspect": 1.543514,
    "category": "paper",
    "status": "available",
    "zoneId": 1,
    "dominantColor": "#8394b4",
    "images": {
      "texture": "/artworks/paper-komposition2/texture.webp",
      "full": "/artworks/paper-komposition2/full.webp",
      "thumb": "/artworks/paper-komposition2/thumb.webp"
    }
  },
  {
    "id": "paper-nazisim-jkh",
    "artistId": "felix",
    "title": "Nazis,im JKH",
    "aspect": 0.729014,
    "category": "paper",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#7c6d64",
    "images": {
      "texture": "/artworks/paper-nazisim-jkh/texture.webp",
      "full": "/artworks/paper-nazisim-jkh/full.webp",
      "thumb": "/artworks/paper-nazisim-jkh/thumb.webp"
    }
  },
  {
    "id": "paper-red-flagsailing",
    "artistId": "felix",
    "title": "Red Flagsailing",
    "aspect": 0.963145,
    "category": "paper",
    "status": "available",
    "zoneId": 1,
    "dominantColor": "#9e8b81",
    "images": {
      "texture": "/artworks/paper-red-flagsailing/texture.webp",
      "full": "/artworks/paper-red-flagsailing/full.webp",
      "thumb": "/artworks/paper-red-flagsailing/thumb.webp"
    }
  },
  {
    "id": "paper-slepplesnights",
    "artistId": "felix",
    "title": "slepplesnights",
    "aspect": 0.922289,
    "category": "paper",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#616a75",
    "images": {
      "texture": "/artworks/paper-slepplesnights/texture.webp",
      "full": "/artworks/paper-slepplesnights/full.webp",
      "thumb": "/artworks/paper-slepplesnights/thumb.webp"
    }
  },
  {
    "id": "paper-taenzer",
    "artistId": "felix",
    "title": "taenzer",
    "aspect": 0.657936,
    "category": "paper",
    "status": "available",
    "zoneId": 1,
    "dominantColor": "#838595",
    "images": {
      "texture": "/artworks/paper-taenzer/texture.webp",
      "full": "/artworks/paper-taenzer/full.webp",
      "thumb": "/artworks/paper-taenzer/thumb.webp"
    }
  },
  {
    "id": "paper-tick-tack-tip",
    "artistId": "felix",
    "title": "Tick Tack Tip",
    "aspect": 1.011786,
    "category": "paper",
    "status": "available",
    "zoneId": 0,
    "dominantColor": "#867a70",
    "images": {
      "texture": "/artworks/paper-tick-tack-tip/texture.webp",
      "full": "/artworks/paper-tick-tack-tip/full.webp",
      "thumb": "/artworks/paper-tick-tack-tip/thumb.webp"
    }
  },
  {
    "id": "paper-vulkan",
    "artistId": "felix",
    "title": "vulkan",
    "aspect": 0.652835,
    "category": "paper",
    "status": "available",
    "zoneId": 1,
    "dominantColor": "#69959f",
    "images": {
      "texture": "/artworks/paper-vulkan/texture.webp",
      "full": "/artworks/paper-vulkan/full.webp",
      "thumb": "/artworks/paper-vulkan/thumb.webp"
    }
  }
]
;

export const generatedZoneMeta = {
  "0": {
    "leadArtworkId": "paper-akt-auf-blau",
    "accentColor": "#756854"
  },
  "1": {
    "leadArtworkId": "paper-red-flagsailing",
    "accentColor": "#9e8b81"
  },
  "2": {
    "leadArtworkId": "paper-die-bande",
    "accentColor": "#3a5877"
  }
} as const;

