from __future__ import annotations

import json
import re
import unicodedata
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PACKS_DIR = ROOT / "artist-packs"
OUT_FILE = ROOT / "src" / "content" / "artist_packs.generated.ts"


def slugify(s: str) -> str:
    s = unicodedata.normalize("NFC", s.strip())
    repl = {
        "ä": "ae",
        "ö": "oe",
        "ü": "ue",
        "Ä": "Ae",
        "Ö": "Oe",
        "Ü": "Ue",
        "ß": "ss",
    }
    for k, v in repl.items():
        s = s.replace(k, v)
    s = unicodedata.normalize("NFKD", s)
    s = "".join(ch for ch in s if not unicodedata.combining(ch))
    s = s.lower()
    s = re.sub(r"[^\w\s-]", "", s)
    s = re.sub(r"[_\s]+", "-", s)
    s = re.sub(r"-{2,}", "-", s)
    return s.strip("-")


def ensure_images(entry: dict) -> dict:
    image = entry.get("image")
    if not image:
        return {
            "texture": entry.get("texture", ""),
            "full": entry.get("full", ""),
            "thumb": entry.get("thumb", ""),
        }
    return {
        "texture": entry.get("texture") or image,
        "full": entry.get("full") or image,
        "thumb": entry.get("thumb") or image,
    }


def strip_none(value):
    if isinstance(value, dict):
        cleaned = {}
        for key, val in value.items():
            if val is None:
                continue
            cleaned[key] = strip_none(val)
        return cleaned
    if isinstance(value, list):
        return [strip_none(item) for item in value if item is not None]
    return value


def load_packs() -> list[dict]:
    packs: list[dict] = []
    if not PACKS_DIR.exists():
        return packs
    for path in sorted(PACKS_DIR.glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        data["_source"] = str(path)
        packs.append(data)
    return packs


def build_pack(raw: dict) -> dict:
    artist_id = raw.get("id") or slugify(raw.get("name", "artist"))
    artist = {
        "id": artist_id,
        "slug": raw.get("slug") or slugify(raw.get("name", artist_id)),
        "name": raw.get("name") or artist_id.title(),
        "bioPdf": raw.get("bioPdf"),
        "bioMarkdown": raw.get("bioMarkdown", ""),
        "contact": raw.get("contact") or {},
        "links": raw.get("links") or [],
        "exhibitions": raw.get("exhibitions") or [],
    }

    rooms = raw.get("rooms") or []

    artworks_out = []
    for a in raw.get("artworks") or []:
        title = a.get("title") or "Untitled"
        base_id = a.get("id") or slugify(f"{artist_id}-{title}")
        images = ensure_images(a)
        artworks_out.append(
            {
                "id": base_id,
                "artistId": artist_id,
                "title": title,
                "year": a.get("year"),
                "medium": a.get("medium"),
                "widthCm": a.get("widthCm"),
                "heightCm": a.get("heightCm"),
                "priceEur": a.get("priceEur"),
                "aspect": a.get("aspect"),
                "category": a.get("category") or "other",
                "status": a.get("status") or "available",
                "zoneId": a.get("zoneId", 0),
                "dominantColor": a.get("dominantColor"),
                "images": images,
                "shopify": a.get("shopify"),
                "infoBox": a.get("infoBox"),
            }
        )

    return {
        "artist": artist,
        "rooms": rooms,
        "artworks": artworks_out,
    }


def main() -> None:
    packs = [strip_none(build_pack(p)) for p in load_packs()]
    generated_at = datetime.now(timezone.utc).isoformat()

    lines = [
        "/* eslint-disable */",
        "// This file is generated by scripts/import_artist_packs.py",
        "// Do not edit by hand; edit JSON in artist-packs/ instead.",
        "",
        'import type { ArtistPack } from "@/content/types";',
        "",
        f'export const generatedAtIso = "{generated_at}";',
        "",
        "export const artistPacks: ArtistPack[] = " + json.dumps(packs, indent=2, ensure_ascii=False) + ";",
        "",
    ]
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
